use ("restaurant");

/*1*/ db.restaurant_queries.find({})
/*2*/db.restaurant_queries.find({}, { "restaurant_id": 1, "name": 1, "borough": 1, "cuisine": 1 })
/*3*/db.restaurant_queries.find({}, {"restaurant_id": 1,"name": 1, "borough": 1, "cuisine": 1, "_id":0 })
/*4*/db.restaurant_queries.find({}, {"restaurant_id": 1,"name": 1, "borough": 1, "zipecode": 1, "_id":0})
/*5*/db.restaurant_queries.find({borough: "Bronx"})
/*6*/db.restaurant_queries.find({borough: "Bronx"}).$limit (5)
/*7*/db.restaurant_queries.find({borough: "Bronx"}).skip(5).$limit (5)
/*8*/db.restaurant_queries.find({"grades.score":{$gt: 90}})
/*9*/db.restaurant_queries.find({"grades.score":{$gt: 80, $lt:100}})
/*10*/db.restaurant_queries.find({"address.coord.0":{$lt: -95.754168}})
/*11*/db.restaurant_queries.find({"cuisine": {$ne: "American"}, "grades.score": {$gt:70}, "address.coord.1":{$lt: -65.754168}})
/*12*/db.restaurant_queries.find({"cuisine": {$ne: "American"}, "grades.score": {$gt:70}, "address.coord.1": {$lt:-65.754168}})
/*13*/db.restaurant_queries.find({"cuisine" : {$ne: "American"}, "grades.grade":"A", borough: {$ne: "Brooklyn"}}).sort({cuisine:-1})
/*14*/db.restaurant_queries.find({name:/^Wil/}, {resturant_id :1, name :1, borough:1, cuisine: 1})
/*15*/db.restaurant_queries.find({name:/ces$/}, {resturant_id :1, name :1, borough:1, cuisine: 1})
/*16*/db.restaurant_queries.find({name:/Reg/}, {resturant_id :1, name :1, borough:1, cuisine: 1})
/*17*/db.restaurant_queries.find({borough:"Bronx", $or: [{cuisine:"American"}, {cuisine: "Chinese"}]})
/*18*/db.restaurant_queries.find ({borough:{$in: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}})
/*19*/db.restaurant_queries.find ({borough:{$nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"]}})
/*20*/db.restaurant_queries.find ({"grades.score": {$lt:10}})